/* Users Managers */
TABLE_ (DB_USER_GROUP)
  INT		(ID) PRIMARY_KEY AUTO_INCREMENT
  STRING_	(USG_NAME, 255)
END_TABLE

TABLE_ (DB_USER)
  INT		(ID) PRIMARY_KEY AUTO_INCREMENT
  STRING_	(USR_NAME, 255)
  STRING_	(USR_LOGIN, 255)
  STRING_	(USR_PASSWORD, 255)
END_TABLE

TABLE_ (DB_USER_REFERENCE)
  INT		(ID) PRIMARY_KEY AUTO_INCREMENT
  INT_		(USG_ID)
  INT_		(USR_ID)
END_TABLE

TABLE_ (DB_USER_ACCESS)
  INT_		(USA_ID) PRIMARY_KEY AUTO_INCREMENT
  INT		(USG_ID)
  STRING_	(USA_NAME,255)
  STRING_	(USA_VALUES,255)
END_TABLE

/****************************************************/

TABLE_ ( DB_TRAY )
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(TRA_NAME ,255)
  INT_		(TRA_GRAIN_COUNT )
END_TABLE

TABLE_ ( DB_WORKSHOP )
  INT_		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT_		(TRA_ID)
  STRING_	(WOR_NAME ,255)
  INT_		(WOR_TRAY_COUNT )
  INT_		(WOR_WORKER_COUNT )
  STRING_	(WOR_CODE ,30)
END_TABLE

TABLE_ (DB_CUSTOMER)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(CUS_CODE ,255)
  STRING_	(CUS_NAME ,222)
  STRING_	(CUS_ADDRESS ,250)
  STRING_	(CUS_PHONE ,30)
  STRING_	(CUS_FAX ,30)
  STRING_	(CUS_CITY ,250)
  STRING_	(CUS_CONTACT ,250)
  STRING_	(CUS_EMAIL ,250)
END_TABLE

TABLE_ (DB_ORDER)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT_		(CUS_ID )
  INT_		(ORD_ID)
  STRING_	(ORD_CODE ,100)
  INT_		(ORD_VALID)
  DATE_		(ORD_DATE )
  STRING_	(ORD_COMMENTAIRE,1024)
END_TABLE

TABLE_ (DB_ORDER_DETAIL)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT_		(DDE_PORTE_ID )
  INT_		(PRV_ID )
  INT		(ORD_ID )
  INT_		(DB_ESPECE_ID )
  INT_		(DB_PESPECE_id )
  DATE_		(ODD_DATE_LIVRAISON )
  DATE_		(ODD_DATE_SEMIS )
  INT_		(ODD_QTE_DEMANDEE )
  INT_		(ODD_QTE_SEMIS )
END_TABLE

TABLE_ (DB_SETTINGS)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT_		(CLS_TYPE)
  STRING_	(CLS_CODE ,255)
  STRING_	(CLS_TEMPLATE ,1024)
END_TABLE

TABLE_ (DB_COMMERCIAL)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(COM_CODE ,255)
  STRING_	(COM_NAME ,250)
  STRING_	(COM_PHONE ,30)
  STRING_	(COM_EMAIL ,250)
END_TABLE

TABLE_ (DB_SPECIE_SETTINGS)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(SPS_NAME ,255)
  INT_		(SPS_TOTAL_DAYS_COUNT )
  INT_		(SPS_TOTAL_WORKER_COUNT )
  DOUBLE_	(SPS_TOTAL_LOSS )
END_TABLE

TABLE_ (DB_SPECIE_SETTINGS_DETAILS)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT_		(SPS_ID )							// DB_SPECIE_SETTINGS ID
  INT_		(SSD_ORDER )						// previous settings
  INT_		(WOR_ID )							// WORKERSHOP ID
  STRING_	(SPS_GREFFE_NAME ,255)
  INT_		(SPS_DAYS_COUNT )
  INT_		(SPS_WORKER_COUNT )
  DOUBLE_	(SPS_LOSS )
END_TABLE

TABLE_ (DB_SPECIE)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT		(SPS_ID )
  INT_		(PRD_ID )
  STRING_	(SPE_NAME ,255)
  INT_		(SPE_TYPE )
END_TABLE

TABLE_ (DB_PROVIDER)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(PRV_CODE ,255)
  STRING_	(PRV_NAME ,255)
  STRING_	(PRV_ADRESSE ,255)
  STRING_	(PRV_CITY ,255)
  STRING_	(PRV_CITY_2 ,30)
  STRING_	(PRV_CONTACT ,255)
  STRING_	(PRV_EMAIL ,255)
END_TABLE

TABLE_ (DB_PRODUCTION)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  INT		(SPS_ID  )
  INT		(WOR_ID  )
  INT_		(RSP_ID  )
  INT_		(ODD_ID  )
  INT_		(PRO_PARENT  )
  STRING_	(PRO_CODE ,255)
  DATE_		(PRO_START_DATE )
  DATE_		(PRO_END_DATE )
  INT_		(PRO_DAY_COUNT )
  INT_		(PRO_START_GRAIN_COUNT )
  INT_		(PRO_END_GRAIN_COUNT )
  INT_		(PRO_WORKER_COUNT )
  DOUBLE_	(PRO_LOSS)
END_TABLE

TABLE_ (DB_PRODECT)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(PRD_CODE ,255)
  STRING_	(PRD_NAME ,255)
END_TABLE

TABLE_ (DB_RESPONSIBLE)
  INT		(ID)  PRIMARY_KEY AUTO_INCREMENT
  STRING_	(RSP_NAME ,255)
  STRING_	(RSP_CODE ,255)
END_TABLE
